async function main() {
  try {
    console.log("Running me");
  } catch (error) {
    console.log(error);
  }
}

main();
